/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package groupproject220marlins;

import java.awt.CardLayout;
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.JTextArea;
import javax.swing.event.CaretEvent;
import javax.swing.event.CaretListener;

/**
 *
 * @author Derek
 */
public class PanelMainForum extends javax.swing.JFrame {

    /**
     * Creates new form TestFrame
     */
    public PanelMainForum() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainDisplayPanel = new javax.swing.JPanel();
        subForumListPanel = new javax.swing.JPanel();
        subForumListBoxScrollPane = new javax.swing.JScrollPane();
        subForumListBox = new javax.swing.JList();
        selectSubForumButton = new javax.swing.JButton();
        forumHeaderLabel = new javax.swing.JLabel();
        subForumViewPanel = new javax.swing.JPanel();
        subForumHeaderLabel = new javax.swing.JLabel();
        threadListScrollPane = new javax.swing.JScrollPane();
        threadListBox = new javax.swing.JList();
        viewThreadButton = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jComboBox2 = new javax.swing.JComboBox();
        subForumsThreadReplyView = new javax.swing.JPanel();
        replySubjectLabel1 = new javax.swing.JLabel();
        replySubjectText = new javax.swing.JLabel();
        replyTextLabel = new javax.swing.JLabel();
        replyTextBoxScrollPane1 = new javax.swing.JScrollPane();
        replyTextBox1 = new javax.swing.JTextArea();
        replyOkCloseButton = new javax.swing.JButton();
        subForumThreadView = new javax.swing.JPanel();
        threadTitleText = new javax.swing.JLabel();
        threadTitleLabel = new javax.swing.JLabel();
        threadSubjectLabel = new javax.swing.JLabel();
        threadSubjectText = new javax.swing.JLabel();
        mainPostTextboxScrollPane = new javax.swing.JScrollPane();
        mainPostTextBox = new javax.swing.JTextArea();
        replyListBoxLabel = new javax.swing.JLabel();
        replySubjectTextBox = new javax.swing.JTextField();
        replySubjectLabel = new javax.swing.JLabel();
        replyTextBoxScrollPane = new javax.swing.JScrollPane();
        replyTextArea = new javax.swing.JTextArea();
        replyContentTextBoxLabel = new javax.swing.JLabel();
        characterCountLabel = new javax.swing.JLabel();
        characterCountData = new javax.swing.JLabel();
        postReplyButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        goToSelectedForumPageButton = new javax.swing.JButton();
        navMenuComboBox1 = new javax.swing.JComboBox();
        viewDetailedSelectedReplButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Java Forum Project");
        setResizable(false);

        mainDisplayPanel.setLayout(new java.awt.CardLayout());

        subForumListBox.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        subForumListBox.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "General Java Discussion", "Java How To Guides", "IDE Tools and Tips", "Off Topic Discussion" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        subForumListBox.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        subForumListBoxScrollPane.setViewportView(subForumListBox);
        subForumListBox.getAccessibleContext().setAccessibleName("subForumListBox");

        selectSubForumButton.setText("Select Sub-Forum");
        selectSubForumButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                selectSubForumButtonMouseClicked(evt);
            }
        });
        selectSubForumButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectSubForumButtonActionPerformed(evt);
            }
        });

        forumHeaderLabel.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        forumHeaderLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        forumHeaderLabel.setText("Welcome To Our Java Forum Project!");

        javax.swing.GroupLayout subForumListPanelLayout = new javax.swing.GroupLayout(subForumListPanel);
        subForumListPanel.setLayout(subForumListPanelLayout);
        subForumListPanelLayout.setHorizontalGroup(
            subForumListPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(subForumListPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(subForumListPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(forumHeaderLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(subForumListPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(subForumListBoxScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(selectSubForumButton, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(291, Short.MAX_VALUE))
        );
        subForumListPanelLayout.setVerticalGroup(
            subForumListPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(subForumListPanelLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(forumHeaderLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(subForumListBoxScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(selectSubForumButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(469, Short.MAX_VALUE))
        );

        selectSubForumButton.getAccessibleContext().setAccessibleName("selectSubForumButton");
        forumHeaderLabel.getAccessibleContext().setAccessibleName("forumHeaderLabel");

        mainDisplayPanel.add(subForumListPanel, "subForumListPanel");
        subForumListPanel.getAccessibleContext().setAccessibleName("");

        subForumViewPanel.setPreferredSize(new java.awt.Dimension(500, 300));

        subForumHeaderLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        subForumHeaderLabel.setText("Sub-Forum Label");

        threadListBox.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        threadListBox.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Thread 1", "Thread 2", "Thread 3", "Thread 4", " " };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        threadListBox.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        threadListScrollPane.setViewportView(threadListBox);

        viewThreadButton.setText("View Thread");
        viewThreadButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewThreadButtonActionPerformed(evt);
            }
        });

        jButton2.setText("Go Now!");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Main Forum View", "Sub Forum View" }));

        javax.swing.GroupLayout subForumViewPanelLayout = new javax.swing.GroupLayout(subForumViewPanel);
        subForumViewPanel.setLayout(subForumViewPanelLayout);
        subForumViewPanelLayout.setHorizontalGroup(
            subForumViewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(subForumViewPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(subForumViewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(threadListScrollPane, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(viewThreadButton, javax.swing.GroupLayout.DEFAULT_SIZE, 616, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, subForumViewPanelLayout.createSequentialGroup()
                        .addComponent(subForumHeaderLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(jButton2)))
                .addContainerGap())
        );
        subForumViewPanelLayout.setVerticalGroup(
            subForumViewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(subForumViewPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(subForumViewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2)
                    .addComponent(subForumHeaderLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(threadListScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(viewThreadButton)
                .addContainerGap(375, Short.MAX_VALUE))
        );

        mainDisplayPanel.add(subForumViewPanel, "subForumViewPanel");

        subForumsThreadReplyView.setMaximumSize(new java.awt.Dimension(500, 210));
        subForumsThreadReplyView.setMinimumSize(new java.awt.Dimension(500, 210));

        replySubjectLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        replySubjectLabel1.setText("Reply Subject :");

        replySubjectText.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        replySubjectText.setText("REPLY SUBJECT TEXT");

        replyTextLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        replyTextLabel.setText("Reply Text :");

        replyTextBox1.setEditable(false);
        replyTextBox1.setColumns(20);
        replyTextBox1.setRows(5);
        replyTextBoxScrollPane1.setViewportView(replyTextBox1);

        replyOkCloseButton.setText("Ok");

        javax.swing.GroupLayout subForumsThreadReplyViewLayout = new javax.swing.GroupLayout(subForumsThreadReplyView);
        subForumsThreadReplyView.setLayout(subForumsThreadReplyViewLayout);
        subForumsThreadReplyViewLayout.setHorizontalGroup(
            subForumsThreadReplyViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(subForumsThreadReplyViewLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(subForumsThreadReplyViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(subForumsThreadReplyViewLayout.createSequentialGroup()
                        .addComponent(replySubjectLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(replySubjectText)
                        .addGap(0, 339, Short.MAX_VALUE))
                    .addGroup(subForumsThreadReplyViewLayout.createSequentialGroup()
                        .addComponent(replyTextLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(subForumsThreadReplyViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(replyOkCloseButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(replyTextBoxScrollPane1))))
                .addContainerGap())
        );
        subForumsThreadReplyViewLayout.setVerticalGroup(
            subForumsThreadReplyViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(subForumsThreadReplyViewLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(subForumsThreadReplyViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(replySubjectLabel1)
                    .addComponent(replySubjectText))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(subForumsThreadReplyViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(replyTextLabel)
                    .addComponent(replyTextBoxScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(replyOkCloseButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        mainDisplayPanel.add(subForumsThreadReplyView, "card5");

        subForumThreadView.setMaximumSize(new java.awt.Dimension(999, 999));
        subForumThreadView.setPreferredSize(new java.awt.Dimension(630, 750));

        threadTitleText.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        threadTitleText.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        threadTitleText.setText("Thread Title Text");

        threadTitleLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        threadTitleLabel.setText("Thread Title :");

        threadSubjectLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        threadSubjectLabel.setText("Thread Subject :");

        threadSubjectText.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        threadSubjectText.setText("Thread Subject Text");

        mainPostTextBox.setEditable(false);
        mainPostTextBox.setColumns(20);
        mainPostTextBox.setRows(5);
        mainPostTextBox.setText("Post Contents Will Be Displayed Here");
        mainPostTextboxScrollPane.setViewportView(mainPostTextBox);

        replyListBoxLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        replyListBoxLabel.setText("Replies :");

        replySubjectTextBox.setText("Fill in reply subject line here...");
        replySubjectTextBox.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                replySubjectTextBoxFocusGained(evt);
            }
        });

        replySubjectLabel.setText("Reply Subject :");

        replyTextBoxScrollPane.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
                replyTextBoxScrollPaneCaretPositionChanged(evt);
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
            }
        });

        replyTextArea.setColumns(20);
        replyTextArea.setRows(5);
        replyTextArea.setText("Max 300 Characters...");
        replyTextArea.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                replyTextAreaFocusGained(evt);
            }
        });
        replyTextBoxScrollPane.setViewportView(replyTextArea);

        replyContentTextBoxLabel.setText("Reply Content :");

        characterCountLabel.setText("Current Character Count :");

        characterCountData.setText("COUNTERLABEL");

        postReplyButton.setText("Post Reply");

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("Select a reply to view content...");
        jScrollPane1.setViewportView(jTextArea1);

        jLabel1.setText("Selected Reply Message:");

        jTextField1.setEditable(false);
        jTextField1.setText("Select a reply to view content...");
        jTextField1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField1FocusGained(evt);
            }
        });

        jLabel2.setText("Selected Reply Subject : ");

        goToSelectedForumPageButton.setText("Go Now!");
        goToSelectedForumPageButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goToSelectedForumPageButtonActionPerformed(evt);
            }
        });

        navMenuComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Main Forum View", "Sub Forum View" }));

        viewDetailedSelectedReplButton.setText("Selected Reply - Detailed View");
        viewDetailedSelectedReplButton.setEnabled(false);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Reply Subject", "Reply Post Date", "Reply User Name", "User Thread Rating"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        jLabel3.setText("Average Rating :");

        jLabel4.setText("avgRate");

        javax.swing.GroupLayout subForumThreadViewLayout = new javax.swing.GroupLayout(subForumThreadView);
        subForumThreadView.setLayout(subForumThreadViewLayout);
        subForumThreadViewLayout.setHorizontalGroup(
            subForumThreadViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(subForumThreadViewLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(subForumThreadViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mainPostTextboxScrollPane)
                    .addGroup(subForumThreadViewLayout.createSequentialGroup()
                        .addGroup(subForumThreadViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(threadTitleLabel)
                            .addComponent(threadSubjectLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(subForumThreadViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(threadTitleText, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(subForumThreadViewLayout.createSequentialGroup()
                                .addComponent(threadSubjectText, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(subForumThreadViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(navMenuComboBox1, 0, 0, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, subForumThreadViewLayout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(goToSelectedForumPageButton))))
                    .addComponent(postReplyButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1)
                    .addComponent(jTextField1)
                    .addComponent(jScrollPane2)
                    .addGroup(subForumThreadViewLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(viewDetailedSelectedReplButton))
                    .addComponent(replySubjectTextBox)
                    .addComponent(replyTextBoxScrollPane)
                    .addGroup(subForumThreadViewLayout.createSequentialGroup()
                        .addGroup(subForumThreadViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(replyListBoxLabel)
                            .addComponent(jLabel1)
                            .addComponent(replySubjectLabel)
                            .addComponent(replyContentTextBoxLabel)
                            .addGroup(subForumThreadViewLayout.createSequentialGroup()
                                .addComponent(characterCountLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(characterCountData)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        subForumThreadViewLayout.setVerticalGroup(
            subForumThreadViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(subForumThreadViewLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(subForumThreadViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(subForumThreadViewLayout.createSequentialGroup()
                        .addGroup(subForumThreadViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(threadTitleText)
                            .addComponent(threadTitleLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(subForumThreadViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(threadSubjectLabel)
                            .addComponent(threadSubjectText)))
                    .addGroup(subForumThreadViewLayout.createSequentialGroup()
                        .addComponent(navMenuComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(subForumThreadViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(goToSelectedForumPageButton)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(mainPostTextboxScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addComponent(replyListBoxLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(subForumThreadViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(viewDetailedSelectedReplButton, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(replySubjectLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(replySubjectTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(replyContentTextBoxLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(replyTextBoxScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(subForumThreadViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(characterCountLabel)
                    .addComponent(characterCountData))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(postReplyButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        mainDisplayPanel.add(subForumThreadView, "subForumThreadView");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mainDisplayPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(mainDisplayPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 662, Short.MAX_VALUE)
                .addContainerGap())
        );

        getAccessibleContext().setAccessibleName("panelMainView");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void selectSubForumButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_selectSubForumButtonMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_selectSubForumButtonMouseClicked

    private void selectSubForumButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectSubForumButtonActionPerformed
        // TODO add your handling code here:
        CardLayout card = (CardLayout) mainDisplayPanel.getLayout();
        this.setSize(670, 350);
        this.setLocation(240, 140);
        card.show(mainDisplayPanel, "subForumViewPanel");
    }//GEN-LAST:event_selectSubForumButtonActionPerformed

    private void viewThreadButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewThreadButtonActionPerformed
        // TODO add your handling code here:
        CardLayout card = (CardLayout) this.mainDisplayPanel.getLayout();
        this.setSize(670, 750);
        this.setLocation(240, 0);

        String text = this.replySubjectTextBox.getText();
        int i = text.length();

        this.characterCountData.setText(Integer.toString(i));
        card.show(mainDisplayPanel, "subForumThreadView");
    }//GEN-LAST:event_viewThreadButtonActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:

        // do my go back based on combo box choice code here
        int i = jComboBox2.getSelectedIndex();
        CardLayout card = (CardLayout) this.mainDisplayPanel.getLayout();
        switch (i) {
            case 0:
                this.setSize(370, 235);
                this.setLocation(240, 240);
                card.show(this.mainDisplayPanel, "subForumListPanel");
                break;

            case 1:
                this.setSize(670, 350);
                this.setLocation(240, 140);
                card.show(this.mainDisplayPanel, "subForumViewPanel");
                break;
        
        }


    }//GEN-LAST:event_jButton2ActionPerformed

    private void goToSelectedForumPageButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goToSelectedForumPageButtonActionPerformed
        // TODO add your handling code here:
        // do my go back based on combo box choice code here
        int i = this.navMenuComboBox1.getSelectedIndex();
        CardLayout card = (CardLayout) this.mainDisplayPanel.getLayout();
        switch (i) {
            case 0:
                this.setSize(370, 235);
                this.setLocation(240, 240);
                card.show(this.mainDisplayPanel, "subForumListPanel");
                break;

            case 1:
                this.setSize(670, 350);
                this.setLocation(240, 140);
                card.show(this.mainDisplayPanel, "subForumViewPanel");
                break;
        }
    }//GEN-LAST:event_goToSelectedForumPageButtonActionPerformed

    private void jTextField1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField1FocusGained
        // TODO add your handling code here:

    }//GEN-LAST:event_jTextField1FocusGained

    private void replyTextBoxScrollPaneCaretPositionChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_replyTextBoxScrollPaneCaretPositionChanged

    }//GEN-LAST:event_replyTextBoxScrollPaneCaretPositionChanged

    private void replyTextAreaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_replyTextAreaFocusGained
        // TODO add your handling code here:
        this.replyTextArea.selectAll();
    }//GEN-LAST:event_replyTextAreaFocusGained

    private void replySubjectTextBoxFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_replySubjectTextBoxFocusGained
        // TODO add your handling code here:
        this.replySubjectTextBox.selectAll();
    }//GEN-LAST:event_replySubjectTextBoxFocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PanelMainForum.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PanelMainForum.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PanelMainForum.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PanelMainForum.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JPanel panels = new JPanel(new CardLayout());
                JFrame mainForumGUI = new PanelMainForum();
                mainForumGUI.setSize(370, 235);
                mainForumGUI.setLocation(240, 240);
                mainForumGUI.setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel characterCountData;
    private javax.swing.JLabel characterCountLabel;
    private javax.swing.JLabel forumHeaderLabel;
    private javax.swing.JButton goToSelectedForumPageButton;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JPanel mainDisplayPanel;
    private javax.swing.JTextArea mainPostTextBox;
    private javax.swing.JScrollPane mainPostTextboxScrollPane;
    private javax.swing.JComboBox navMenuComboBox1;
    private javax.swing.JButton postReplyButton;
    private javax.swing.JLabel replyContentTextBoxLabel;
    private javax.swing.JLabel replyListBoxLabel;
    private javax.swing.JButton replyOkCloseButton;
    private javax.swing.JLabel replySubjectLabel;
    private javax.swing.JLabel replySubjectLabel1;
    private javax.swing.JLabel replySubjectText;
    private javax.swing.JTextField replySubjectTextBox;
    private javax.swing.JTextArea replyTextArea;
    private javax.swing.JTextArea replyTextBox1;
    private javax.swing.JScrollPane replyTextBoxScrollPane;
    private javax.swing.JScrollPane replyTextBoxScrollPane1;
    private javax.swing.JLabel replyTextLabel;
    private javax.swing.JButton selectSubForumButton;
    private javax.swing.JLabel subForumHeaderLabel;
    private javax.swing.JList subForumListBox;
    private javax.swing.JScrollPane subForumListBoxScrollPane;
    private javax.swing.JPanel subForumListPanel;
    private javax.swing.JPanel subForumThreadView;
    private javax.swing.JPanel subForumViewPanel;
    private javax.swing.JPanel subForumsThreadReplyView;
    private javax.swing.JList threadListBox;
    private javax.swing.JScrollPane threadListScrollPane;
    private javax.swing.JLabel threadSubjectLabel;
    private javax.swing.JLabel threadSubjectText;
    private javax.swing.JLabel threadTitleLabel;
    private javax.swing.JLabel threadTitleText;
    private javax.swing.JButton viewDetailedSelectedReplButton;
    private javax.swing.JButton viewThreadButton;
    // End of variables declaration//GEN-END:variables
}
